// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer.Models;

public partial class Answer
{
    public Guid AnswerId { get; set; }

    public Guid QuestionId { get; set; }

    public Guid ReviewerId { get; set; }

    public string AnswerContent { get; set; }

    public DateTime? AnsweredAt { get; set; }

    public virtual Question Question { get; set; }

    public virtual User Reviewer { get; set; }
}