// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer.Models;

public partial class Group
{
    public Guid GroupId { get; set; }

    public string GroupName { get; set; }

    public Guid TopicId { get; set; }

    public Guid SupervisorId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();

    public virtual User Supervisor { get; set; }

    public virtual Topic Topic { get; set; }

    public virtual ICollection<User> Students { get; set; } = new List<User>();
}