// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer.Models;

public partial class Question
{
    public Guid QuestionId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public string Status { get; set; }

    public string RejectReason { get; set; }

    public Guid CreatedBy { get; set; }

    public Guid GroupId { get; set; }

    public Guid TopicId { get; set; }

    public Guid? ApprovedBy { get; set; }

    public DateTime? ApprovedAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Answer Answer { get; set; }

    public virtual User ApprovedByNavigation { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual Group Group { get; set; }

    public virtual Topic Topic { get; set; }
}