// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer.Models;

public partial class Topic
{
    public Guid TopicId { get; set; }

    public string TopicName { get; set; }

    public string Description { get; set; }

    public Guid ReviewerId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Group> Groups { get; set; } = new List<Group>();

    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();

    public virtual User Reviewer { get; set; }
}